"""
Report Generator Module

Generate network reports in various formats:
- Markdown reports
- PDF export
- Network health summaries
"""
import os
import json
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional
from dataclasses import dataclass

# PDF generation will be optional
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


@dataclass
class ReportData:
    """Data for report generation"""
    title: str
    period: str
    generated_at: str
    sections: List[Dict[str, Any]]


class ReportGenerator:
    """
    Generate network reports
    
    Features:
    - Markdown report generation
    - PDF export (with ReportLab)
    - Device status summaries
    - Alert summaries
    - Network health reports
    """
    
    def __init__(self, reports_dir: str = None):
        if reports_dir is None:
            reports_dir = os.path.join(
                os.path.dirname(__file__), 
                "..", 
                "data", 
                "reports"
            )
        
        os.makedirs(reports_dir, exist_ok=True)
        self.reports_dir = reports_dir
    
    def generate_network_health_report(self, period: str = "today") -> str:
        """
        Generate a network health report
        
        Args:
            period: today, week, month
        
        Returns:
            Markdown report
        """
        from agent.infrastructure import infrastructure
        from agent.alerting import alert_manager
        
        now = datetime.now()
        
        # Get device data
        devices = infrastructure.list_devices()
        online = sum(1 for d in devices if d.status and d.status.value == "online")
        offline = sum(1 for d in devices if d.status and d.status.value == "offline")
        
        # Get alert data
        alerts = alert_manager.get_alerts(limit=50)
        critical = sum(1 for a in alerts if a.severity.value == "critical")
        warnings = sum(1 for a in alerts if a.severity.value == "warning")
        
        # Build report
        report = f"""# 📊 Network Health Report

**Generated:** {now.strftime('%Y-%m-%d %H:%M')}
**Period:** {period.title()}

---

## 📈 Executive Summary

| Metric | Value | Status |
|--------|-------|--------|
| Total Devices | {len(devices)} | - |
| Online | {online} | {'✅' if online > 0 else '⚠️'} |
| Offline | {offline} | {'❌' if offline > 0 else '✅'} |
| Critical Alerts | {critical} | {'🚨' if critical > 0 else '✅'} |
| Warnings | {warnings} | {'⚠️' if warnings > 0 else '✅'} |

---

## 🖥️ Device Status

"""
        if devices:
            report += "| Device | IP | Type | Status | Uptime |\n"
            report += "|--------|-------|------|--------|--------|\n"
            for d in devices[:20]:
                status = d.status.value if d.status else "unknown"
                status_icon = "✅" if status == "online" else "❌" if status == "offline" else "⚠️"
                uptime = f"{d.uptime_percent:.1f}%" if hasattr(d, 'uptime_percent') else "N/A"
                report += f"| {d.name} | {d.ip} | {d.device_type.value} | {status_icon} {status} | {uptime} |\n"
        else:
            report += "_No devices registered_\n"
        
        report += """
---

## 🚨 Recent Alerts

"""
        if alerts:
            for a in alerts[:10]:
                icon = "🚨" if a.severity.value == "critical" else "⚠️" if a.severity.value == "warning" else "ℹ️"
                ack = "✓" if a.acknowledged else ""
                report += f"- {icon} **{a.severity.value.upper()}** {ack}: {a.message[:60]}... _{a.timestamp[:16]}_\n"
        else:
            report += "_No recent alerts_ ✅\n"
        
        report += """
---

## 📋 Recommendations

"""
        # Generate recommendations
        if offline > 0:
            report += f"- 🔧 **{offline} device(s) offline** - investigate connectivity issues\n"
        if critical > 0:
            report += f"- 🚨 **{critical} critical alert(s)** - immediate attention required\n"
        if warnings > 0:
            report += f"- ⚠️ **{warnings} warning(s)** - review and address as needed\n"
        if offline == 0 and critical == 0 and warnings == 0:
            report += "- ✅ **All systems healthy** - continue monitoring\n"
        
        report += f"""
---

_Report generated by NetOps Sentinel Agent_
"""
        
        return report
    
    def generate_device_report(self, device_id: str) -> str:
        """Generate a report for a specific device"""
        from agent.infrastructure import infrastructure
        from agent.config_backup import config_backup
        from agent.scheduler import scheduler
        
        device = infrastructure.get_device(device_id)
        if not device:
            return f"❌ Device '{device_id}' not found"
        
        now = datetime.now()
        
        # Get config backup info
        config_versions = config_backup.get_versions(device_id)
        latest_config = config_backup.get_latest_version(device_id)
        
        # Get last health check
        last_check = scheduler.get_last_result(device_id)
        
        report = f"""# 📱 Device Report: {device.name}

**Generated:** {now.strftime('%Y-%m-%d %H:%M')}

---

## 📋 Device Information

| Property | Value |
|----------|-------|
| **Name** | {device.name} |
| **IP Address** | {device.ip} |
| **Type** | {device.device_type.value} |
| **Status** | {device.status.value if device.status else 'Unknown'} |
| **Location** | {device.location or 'Not specified'} |
| **Description** | {device.description or 'None'} |

---

## 🔍 Health Check

"""
        if last_check:
            report += f"**Last Check:** {last_check.timestamp[:19]}\n"
            report += f"**Ping:** {'✅ OK' if last_check.ping_ok else '❌ Failed'}\n"
            if last_check.ping_ok:
                report += f"**Latency:** {last_check.ping_latency_ms:.1f}ms\n"
            if last_check.ports_open:
                report += f"**Open Ports:** {', '.join(map(str, last_check.ports_open))}\n"
            if last_check.ports_closed:
                report += f"**Closed Ports:** {', '.join(map(str, last_check.ports_closed))}\n"
        else:
            report += "_No health check data available_\n"
        
        report += """
---

## 💾 Configuration Backups

"""
        if config_versions:
            report += f"**Total Versions:** {len(config_versions)}\n\n"
            report += "| Version | Date | Size |\n"
            report += "|---------|------|------|\n"
            for v in config_versions[:5]:
                report += f"| v{v.version} | {v.timestamp[:10]} | {v.size_bytes:,} bytes |\n"
        else:
            report += "_No configuration backups_\n"
        
        report += f"""
---

_Device report generated by NetOps Sentinel Agent_
"""
        
        return report
    
    def export_to_pdf(self, markdown_content: str, filename: str) -> Optional[str]:
        """Export markdown report to PDF"""
        if not HAS_REPORTLAB:
            return None
        
        filepath = os.path.join(self.reports_dir, filename)
        
        try:
            doc = SimpleDocTemplate(
                filepath,
                pagesize=A4,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=72
            )
            
            styles = getSampleStyleSheet()
            
            # Add custom styles
            styles.add(ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=18,
                spaceAfter=30
            ))
            
            story = []
            
            # Parse markdown and convert to PDF elements
            lines = markdown_content.split('\n')
            
            for line in lines:
                line = line.strip()
                
                if not line:
                    story.append(Spacer(1, 12))
                elif line.startswith('# '):
                    story.append(Paragraph(line[2:], styles['CustomTitle']))
                elif line.startswith('## '):
                    story.append(Paragraph(line[3:], styles['Heading2']))
                elif line.startswith('### '):
                    story.append(Paragraph(line[4:], styles['Heading3']))
                elif line.startswith('---'):
                    story.append(Spacer(1, 20))
                elif line.startswith('- '):
                    story.append(Paragraph(f"• {line[2:]}", styles['Normal']))
                elif line.startswith('|'):
                    pass  # Skip tables for now
                elif line.startswith('**') and line.endswith('**'):
                    story.append(Paragraph(f"<b>{line[2:-2]}</b>", styles['Normal']))
                else:
                    # Clean up markdown formatting
                    clean = line.replace('**', '').replace('_', '').replace('`', '')
                    if clean:
                        story.append(Paragraph(clean, styles['Normal']))
            
            doc.build(story)
            return filepath
            
        except Exception as e:
            print(f"PDF export error: {e}")
            return None
    
    def generate_weekly_summary(self) -> str:
        """Generate a weekly summary report"""
        from agent.alerts import alert_manager
        from agent.long_term_memory import long_term_memory
        
        now = datetime.now()
        week_ago = now - timedelta(days=7)
        
        # Get memory stats
        memory_stats = long_term_memory.get_memory_stats()
        
        # Get alert summary
        alert_summary = alert_manager.get_summary()
        
        report = f"""# 📅 Weekly Network Summary

**Week Ending:** {now.strftime('%Y-%m-%d')}
**Period:** {week_ago.strftime('%Y-%m-%d')} to {now.strftime('%Y-%m-%d')}

---

## 📊 Overview

This week's network activity summary.

---

## 🧠 Agent Learning

| Metric | Count |
|--------|-------|
| Solutions Learned | {memory_stats['solutions_stored']} |
| Solution Uses | {memory_stats['total_solution_uses']} |
| Patterns Detected | {memory_stats['patterns_learned']} |

---

## 🚨 Alert Summary

| Severity | Count |
|----------|-------|
| Critical | {alert_summary.get('by_severity', {}).get('critical', 0)} |
| Warning | {alert_summary.get('by_severity', {}).get('warning', 0)} |
| Info | {alert_summary.get('by_severity', {}).get('info', 0)} |
| **Total** | {alert_summary.get('total', 0)} |

---

## 💡 Recommendations

Based on this week's data:

1. Review any unacknowledged alerts ({alert_summary.get('unacknowledged', 0)} pending)
2. Check device health status regularly
3. Update configuration backups for critical devices

---

_Weekly summary generated by NetOps Sentinel Agent_
"""
        
        return report
    
    def save_report(self, content: str, name: str, format: str = "md") -> str:
        """Save report to file"""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"{name}_{timestamp}.{format}"
        filepath = os.path.join(self.reports_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        return filepath


# Singleton instance
report_generator = ReportGenerator()
